# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, cmdargs, filepath, text }:

cabal.mkDerivation (self: {
  pname = "bindings-saga-cmd";
  version = "0.1.0.0";
  src = ./.;
  isLibrary = true;
  isExecutable = true;
  buildDepends = [ cmdargs filepath text ];
  meta = {
    homepage = "https://github.com/michelk/bindings-saga-cmd";
    description = "Wrapping saga_cmd";
    license = self.stdenv.lib.licenses.gpl3;
    platforms = self.ghc.meta.platforms;
  };
})
